name: Build & deploy Next.js app to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🌱 Checkout to the branch
        uses: actions/checkout@v4

      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: ⚙️ npm install and build
        run: |
          cd ./src
          npm install
          npm run build --if-present
          cd ..

      - name: 📂 Copy standalone into the root
        run: mkdir -p ./site-deploy && cp -R ./src/.next/standalone/* ./site-deploy

      - name: 📂 Copy static into the .next folder
        run: mkdir -p ./site-deploy/.next && cp -R ./src/.next/static ./site-deploy/.next/static

      - name: 📂 Copy Public folder
        run: mkdir -p ./site-deploy/public && cp -R ./src/public/* ./site-deploy/public

      - name: 📦 Package Next application
        run: |
          cd ./site-deploy
          zip -r Nextjs-site.zip ./*
          cd ..

      - name: 🔍 Diagnostics
        run: |
          ls ./src
          ls ./src/.next
          ls ./site-deploy

      - name: ⬆️ Publish Next Application artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nextjs-site
          path: ./site-deploy/Nextjs-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: ⬇️ Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: Nextjs-site

      - name: 🗝️ Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔧 Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            webapp_name="${{ secrets.AZURE_APP_SERVICE_NAME }}"
            echo "Web App Name: $webapp_name"
            rg=$(az webapp list --query "[?name=='$webapp_name'].resourceGroup" --output tsv)
            echo "Resource Group: $rg"
            
            if [ -z "$rg" ]; then
              echo "Resource group not found for web app $webapp_name"
              exit 1
            fi
            
            echo "Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service $webapp_name in resource group $rg"
            az webapp config appsettings set -n $webapp_name -g $rg --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false -o none
            
            echo "Setting --startup-file=\"node server.js\" on app service $webapp_name in resource group $rg"
            az webapp config set --startup-file="node server.js" -n $webapp_name -g $rg -o none
            
            sleep 10

      - name: 🚀 Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: ./Nextjs-site.zip

      - name: 🧹 Cleanup
        run: rm ./Nextjs-site.zip
